name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t <docker_hub_username>/flask-app:latest .
        docker push <docker_hub_username>/flask-app:latest

    - name: Deploy to Render
      run: |
        curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"serviceId":"<your_service_id>"}' \
        https://api.render.com/v1/services/<your_service_id>/deploys
